<a href="https://colab.research.google.com/github/ghluque/Import-data-from-PDF/blob/main/Import_data_from_PDF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import data from PDF with TABULA

In [7]:
!pip install -q tabula-py
# Install tabula

In [8]:
import tabula
import pandas as pd

In [9]:
url = 'https://www.indec.gob.ar/uploads/informesdeprensa/ingresos_3trim23AE11D74D73.pdf'
# We declare the url as a variable

In [13]:
data = tabula.read_pdf(url, stream=True, pages=5)
#Read the document. The data is on page 5
data

[             Unnamed: 0  Escala de ingreso              Población  \
 0                 Decil                NaN                    NaN
 1                   NaN                NaN   Población Porcentaje
 2                   NaN        Desde Hasta                    NaN
 3                   NaN                NaN  por decil de personas
 4                   NaN                NaN                    NaN
 5                   NaN                NaN                    NaN
 6                   NaN                $ $                      %
 7                     1           0 31.917         2.949.926 10,0
 8                     2      31.917 45.000         2.943.062 10,0
 9                     3      45.000 58.400         2.951.618 10,0
 10                    4      58.400 74.750         2.941.048 10,0
 11                    5      74.750 91.000         2.946.595 10,0
 12                    6     91.000 110.000         2.947.304 10,0
 13                    7    110.000 136.250         2.946.884 10,0
 14                    8    136.250 178.750         2.945.788 10,0
 15                    9    178.750 247.500         2.950.138 10,0
 16                   10  247.500 4.205.000         2.941.395 10,0
 17  Población total (1)                NaN       29.463.758 100,0

        Unnamed: 1 Ingreso per cápita familiar   Unnamed: 2
 0         Ingreso             Ingreso Ingreso          NaN
 1       total por                  Porcentaje  Mediana por
 2             NaN         medio por medio por          NaN
 3           decil                 del ingreso        decil
 4             NaN               decil estrato          NaN
 5      (en miles)                         NaN          NaN
 6               $                       % $ $            $
 7      61.488.898                  1,7 20.844       23.333
 8     111.223.646                  3,1 37.792       37.222
 9     151.340.806                  4,2 51.274       50.750
 10    194.307.491           5,3 66.067 43.982       66.667
 11    243.809.614                  6,7 82.743       82.500
 12    296.519.072                 8,1 100.607      100.000
 13    359.734.554                 9,9 122.073      120.000
 14    454.182.975        12,5 154.180 114.897      150.000
 15    612.527.793                16,8 207.627      202.000
 16  1.155.815.555        31,7 392.948 300.150      325.000
 17  3.640.950.401       100,0 123.574 123.574       91.000  ]

In [16]:
tab = pd.DataFrame(tabula.read_pdf(url, pages =5)[0])
#Convert data in Dataframe

In [18]:
tab.head()
#Show head

,Unnamed: 0,Escala de ingreso,Población,Unnamed: 1,Ingreso per cápita familiar,Unnamed: 2
0,Decil,NaN,NaN,Ingreso,Ingreso Ingreso,NaN
1,NaN,NaN,Población Porcentaje,total por,Porcentaje,Mediana por
2,NaN,Desde Hasta,NaN,NaN,medio por medio por,NaN
3,NaN,NaN,por decil de personas,decil,del ingreso,decil
4,NaN,NaN,NaN,NaN,decil estrato,NaN
5,NaN,NaN,NaN,(en miles),NaN,NaN
6,NaN,$ $,%,$,% $ $,$
7,1,0 31.917,"2.949.926 10,0",61.488.898,"1,7 20.844",23.333
8,2,31.917 45.000,"2.943.062 10,0",111.223.646,"3,1 37.792",37.222
9,3,45.000 58.400,"2.951.618 10,0",151.340.806,"4,2 51.274",50.750
10,4,58.400 74.750,"2.941.048 10,0",194.307.491,"5,3 66.067 43.982",66.667
11,5,74.750 91.000,"2.946.595 10,0",243.809.614,"6,7 82.743",82.500
12,6,91.000 110.000,"2.947.304 10,0",296.519.072,"8,1 100.607",100.000
13,7,110.000 136.250,"2.946.884 10,0",359.734.554,"9,9 122.073",120.000
14,8,136.250 178.750,"2.945.788 10,0",454.182.975,"12,5 154.180 114.897",150.000
15,9,178.750 247.500,"2.950.138 10,0",612.527.793,"16,8 207.627",202.000
16,10,247.500 4.205.000,"2.941.395 10,0",1.155.815.555,"31,7 392.948 300.150",325.000
17,Población total (1),NaN,"29.463.758 100,0",3.640.950.401,"100,0 123.574 123.574",91.000